'use client';
import React, { useState } from 'react';

const assignmentModules = [
  {
    id: 'reflection', icon: '💭', title: 'Reflection Generator',
    desc: 'Generate structured reflective writing based on clinical experiences',
    fields: [
      { label: 'Clinical Experience / Event', placeholder: 'e.g., Observed a liver transplant surgery...', type: 'textarea' },
      { label: 'Reflection Framework', placeholder: '', type: 'select', options: ["Gibbs' Reflective Cycle", "Kolb's Experiential Learning", "Johns' Model", "Driscoll's Model"] },
    ]
  },
  {
    id: 'seminar', icon: '🎤', title: 'Seminar Builder',
    desc: 'Build structured seminar presentations with slides outline',
    fields: [
      { label: 'Seminar Topic', placeholder: 'e.g., Antimicrobial Stewardship in Clinical Practice', type: 'text' },
      { label: 'Duration (minutes)', placeholder: '20', type: 'text' },
    ]
  },
  {
    id: 'case', icon: '🏥', title: 'Case Presentations',
    desc: 'Create structured clinical case presentations from patient data',
    fields: [
      { label: 'Chief Complaint', placeholder: 'e.g., 45-year-old male with chest pain and shortness of breath...', type: 'textarea' },
      { label: 'Specialty', placeholder: '', type: 'select', options: ['Medicine', 'Surgery', 'Paediatrics', 'Obstetrics', 'Psychiatry'] },
    ]
  },
  {
    id: 'litreview', icon: '📰', title: 'Literature Review',
    desc: 'Generate structured literature review outlines on medical topics',
    fields: [
      { label: 'Research Topic / Question', placeholder: 'e.g., Effectiveness of ACE inhibitors in diabetic nephropathy', type: 'textarea' },
      { label: 'Review Type', placeholder: '', type: 'select', options: ['Narrative Review', 'Systematic Review', 'Meta-analysis', 'Scoping Review'] },
    ]
  },
  {
    id: 'topicsummary', icon: '📑', title: 'Topic Summary',
    desc: 'Generate concise yet comprehensive topic summaries',
    fields: [
      { label: 'Topic to Summarize', placeholder: 'e.g., Management of acute myocardial infarction', type: 'text' },
      { label: 'Word Limit', placeholder: '', type: 'select', options: ['300 words', '500 words', '800 words', '1000 words'] },
    ]
  },
];

export default function AssignmentMSPage() {
  const [active, setActive] = useState(assignmentModules[0].id);
  const [inputs, setInputs] = useState<Record<string, string>>({});
  const [generating, setGenerating] = useState(false);
  const [output, setOutput] = useState('');

  const activeModule = assignmentModules.find(m => m.id === active)!;

  const generate = async () => {
    setGenerating(true);
    await new Promise(r => setTimeout(r, 2500));
    setOutput(`**AI-Generated ${activeModule.title} Output**

This is a comprehensive, structured ${activeModule.title.toLowerCase()} based on your input. The following content is generated using advanced AI aligned with university standards and clinical best practices.

**Section 1: Introduction**
[Detailed introduction contextualizing the topic and its relevance to medical education and clinical practice]

**Section 2: Main Content**
The core content covers all essential aspects including theoretical foundations, practical applications, and evidence-based approaches. This section is structured to meet examination standards while ensuring clinical applicability.

**Section 3: Analysis & Discussion**
A critical analysis of the subject matter, including both supportive evidence and areas of ongoing research. Alternative viewpoints are presented with balanced commentary.

**Section 4: Clinical Implications**
Direct relevance to clinical practice, patient care, and healthcare outcomes. Practical takeaways for the undergraduate medical student.

**Section 5: Conclusion**
A concise summary capturing the key learning points and their significance for examination and clinical practice.

**References (Key Sources):**
1. Harrison's Principles of Internal Medicine, 21st Edition
2. Oxford Handbook of Clinical Medicine, 10th Edition
3. Recent peer-reviewed article (2024) in relevant specialty journal

*Generated by UGMentor AI • Task Builder*`);
    setGenerating(false);
  };

  const updateInput = (label: string, value: string) => setInputs(prev => ({ ...prev, [label]: value }));

  return (
    <div className="page-container">
      <div className="page-header">
        <h1 className="page-title font-outfit">📋 Task Builder</h1>
        <p className="page-desc">AI-powered assignment generation tools for medical education</p>
      </div>

      <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
        {/* Module selector */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, width: 220, flexShrink: 0 }}>
          {assignmentModules.map(m => (
            <button key={m.id} onClick={() => { setActive(m.id); setOutput(''); setInputs({}); }}
              style={{
                display: 'flex', alignItems: 'center', gap: 10, padding: '12px 14px',
                background: active === m.id ? 'rgba(108,59,255,0.15)' : 'var(--bg-card)',
                border: `1px solid ${active === m.id ? 'rgba(108,59,255,0.4)' : 'var(--border)'}`,
                borderRadius: 'var(--radius-md)', cursor: 'pointer', transition: 'var(--transition)', textAlign: 'left'
              }}>
              <span style={{ fontSize: 22 }}>{m.icon}</span>
              <span style={{ fontSize: 13, fontWeight: active === m.id ? 700 : 500, color: active === m.id ? 'var(--primary-light)' : 'var(--text-secondary)' }}>
                {m.title}
              </span>
            </button>
          ))}
        </div>

        {/* Active module */}
        <div style={{ flex: 1, minWidth: 300 }}>
          <div className="card" style={{ marginBottom: 16 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
              <div style={{ width: 48, height: 48, background: 'rgba(108,59,255,0.15)', borderRadius: 'var(--radius-md)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 26 }}>{activeModule.icon}</div>
              <div>
                <div style={{ fontSize: 18, fontWeight: 700 }}>{activeModule.title}</div>
                <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{activeModule.desc}</div>
              </div>
            </div>

            {activeModule.fields.map(field => (
              <div key={field.label} className="form-group">
                <label className="label">{field.label}</label>
                {field.type === 'textarea' ? (
                  <textarea className="input-field" rows={4} placeholder={field.placeholder}
                    value={inputs[field.label] || ''} onChange={e => updateInput(field.label, e.target.value)} />
                ) : field.type === 'select' ? (
                  <select className="input-field" value={inputs[field.label] || ''} onChange={e => updateInput(field.label, e.target.value)}>
                    <option value="">Select…</option>
                    {field.options?.map(o => <option key={o}>{o}</option>)}
                  </select>
                ) : (
                  <input className="input-field" placeholder={field.placeholder}
                    value={inputs[field.label] || ''} onChange={e => updateInput(field.label, e.target.value)} />
                )}
              </div>
            ))}

            <button className="btn btn-primary" style={{ width: '100%', justifyContent: 'center' }}
              onClick={generate} disabled={generating}>
              {generating ? <><span className="spinner" />Generating…</> : `🤖 Generate ${activeModule.title}`}
            </button>
          </div>

          {output && (
            <div className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
                <div style={{ fontWeight: 700 }}>✨ Generated Output</div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <button className="btn btn-secondary btn-sm">📋 Copy</button>
                  <button className="btn btn-secondary btn-sm">💾 Save</button>
                  <button className="btn btn-secondary btn-sm">🖨️ Print</button>
                </div>
              </div>
              <div className="ai-response" style={{ maxHeight: 500, overflowY: 'auto' }}>{output}</div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
